### ISSUE TITLE
Don't load full object history all at once

### ISSUE THREAD

**Issue by 501Ghost** [Zaczero/openstreetmap-ng#18]
Hi. I just looked at https://www.openstreetmap.org/user/NorthCrab/diary/404106 and it looks very promising. Keep up the good work!

One issue I currently have with loading osm.org is that it is impossible to load the history of any (large) object with more than a couple hundred versions (usually admin boundaries). The website tries to load all of the versions at once and simply quits halfway. For OpenStreetMap NextGen, can you make it so that only the last 20 or so versions are loaded at first and you can load 20 more each time you click on "Load more", just like with the "history" page (https://www.openstreetmap.org/history)?

(I don't hang around on Github much, so forgive me if the title is unhelpful or I forgot any other etiquette or info)

**Comment by Zaczero** [comment]
Hello and Thank You for the interest!

On this screenshot you will see there is a pagination control at the bottom of the list:

![image](https://github.com/Zaczero/openstreetmap-ng/assets/10835147/9aa4946e-dae0-4f7e-a364-e9d4f15c7e31)

Each page currently contains 10 history versions but it's easy to change :slightly_smiling_face:

**Comment by Zaczero** [comment]
btw. if you have other cool ideas, feel free to share *(and possibly contribute in June)* :sunglasses:

**Comment by 501Ghost** [comment]
That's great to know.
