### ISSUE TITLE
typo in f-string

### ISSUE THREAD

**Issue by opk12** [Zaczero/openstreetmap-ng#20]
`scripts/preload.load.py:63` has a syntax error, should use `"` around either the f-string or the `,`.

**Comment by Zaczero** [comment]
Hello! Please wait until the end of May with contributions, as I am still finishing up some core parts of the code and documentation :slightly_smiling_face:. Then, I'll be able to help you. You can leave this issue open and I'll let you know when the contributor documentation is ready and the project is open.

**Comment by Zaczero** [comment]
Hello again! The project is now open for contributions and I'll now provide support. Please check out the [Contributor Guide](https://github.com/Zaczero/openstreetmap-ng/wiki/Contributing:-Getting-Started) and let me know if that clarifies things! At the time of your posting this guide did not exist.

**Comment by starsep** [comment]
It's about this line: https://github.com/Zaczero/openstreetmap-ng/blob/8363ef040dc2cc3627b34581d9aa75fbdc53eac4/scripts/preload_load.py#L63

Smaller example:
``` python
from app.models.db.changeset import Changeset
from app.models.db.element import Element
from app.models.db.element_member import ElementMember
from app.models.db.user import User
tables = (User, Changeset, Element, ElementMember)
print(f'TRUNCATE {','.join(f'"{t.__tablename__}"' for t in tables)} RESTART IDENTITY CASCADE')
```

It works correctly in Python 3.12+.
It doesn't work in in Python 3.11 or older
Error:
```
    print(f'TRUNCATE {','.join(f'"{t.__tablename__}"' for t in tables)} RESTART IDENTITY CASCADE')
                       ^
SyntaxError: f-string: expecting '}'
```

**Comment by Zaczero** [comment]
I'll close this issue because it seems to be answered and there's no more activity :+1:
