### ISSUE TITLE
Inform about how much disk space is claimed while preloading the database

### ISSUE THREAD

**Issue by kkalata** [Zaczero/openstreetmap-ng#33]
[The contribution guide](https://github.com/Zaczero/openstreetmap-ng/wiki/Contributing:-Getting-Started#6-preloading-the-database-optional) should inform contributors about amount of disk space claimed on preloading process, especially by the decompressed database. This way they wouldn't be suprised by little or no free space left.

**Comment by starsep** [comment]
On my machine (3900X, 32GB, SSD) preloading took 114 minutes.
Disk used after script finished is 297GB.
During preloading the largest value I have noticed was 306GB

Perhaps
```
Preloaded data requires a lot of free storage.
Make sure you have over 300GB of free space before running this script.
```
