### ISSUE TITLE
Method for deleting notes without any comments

### ISSUE THREAD

**Issue by Zaczero** [Zaczero/openstreetmap-ng#41]
The goal is to:
- Write a method in NoteService that will find and delete all notes without comments (single database call)
- This method will not be called from anywhere initially
- In TestService create a method that will artificially create a note without comments
- Write a test for successful empty note deletion

**Comment by tomekrzymyszkiewicz** [comment]
By "Write a test for successful empty note deletion" you mean unit tests?

**Comment by Zaczero** [comment]
TYVM! Since this is your first bounty, you can keep collecting the funds and let me know whenever you would like to withdraw. It's tracked [here](https://github.com/Zaczero/openstreetmap-ng/wiki/Ledger).

**Comment by tomekrzymyszkiewicz** [comment]
You're welcome. Looking forward to create more PRs!
