### ISSUE TITLE
Trace visualization on a leaflet map

### ISSUE THREAD

**Issue by Zaczero** [Zaczero/openstreetmap-ng#5]
Currently, it's just a plain background and provides no useful point of reference:

![image](https://github.com/Zaczero/openstreetmap-ng/assets/10835147/c4bb1233-e899-410a-9291-5b70745681cd)

The goal is to:

- Display trace on an interactive leaflet map
- Make it possible to pan around/zoom
- Animate trace with ant-path or similar (useful: https://rubenspgcavalcante.github.io/leaflet-ant-path)

**Comment by docentYT** [comment]
I'll do that.

**Comment by Zaczero** [comment]
Thank you for your work! The ledger has been updated.
