### ISSUE TITLE
Add help text to export panel

### ISSUE THREAD

**Issue by Zaczero** [Zaczero/openstreetmap-ng#51]
![image](https://github.com/Zaczero/openstreetmap-ng/assets/10835147/f8efa5f9-69a8-4164-882f-f238072f9c06)

Basically, we want a (tip: form-text) below the download button explaining that the exported image will not contain any navigation markers and other elements. It will contain just the plain map. I don't have any specific ideas on how the text should be formulated.

The goal is to:
- Create a new translation string in config/locale/extra_en.yaml
- Include the new string and HTML formatting in share sidebar template

**Comment by docentYT** [comment]
![obraz](https://github.com/Zaczero/openstreetmap-ng/assets/63965954/b36fa2ee-3516-41f8-ace5-312e16813556)

**Comment by Zaczero** [comment]
Solid! Since this is your first bounty, you can keep collecting the funds and let me know whenever you would like to withdraw. It's tracked [here](https://github.com/Zaczero/openstreetmap-ng/wiki/Ledger).
