### ISSUE TITLE
Analysis: Is it safe to remove uselang param from wiki URLs

### ISSUE THREAD

**Issue by Zaczero** [Zaczero/openstreetmap-ng#63]
When generating wiki links, we always include uselang parameter, hinting to the wiki what language should the page be displayed in. However, my intuition tells me that wikis are already smart enough to determine it on their own.

The goal is to:
- Determine if uselang can be safely removed, without affecting user experience (provide some evidence)
- If so, remove all uselang code references

**Comment by docentYT** [comment]
The osm wiki uses MediaWiki, which by default uses the browser language for the interface [(code)](https://github.com/wikimedia/mediawiki/blob/6cbd9e52638b471fa139b852bf5f8d5d366cfff0/resources/lib/jquery.i18n/src/jquery.i18n.js#L256). This language can be changed using the `&uselang` parameter [(source)](https://www.mediawiki.org/wiki/Manual:Language). 

I would like to point out that in openstreetmap the user can select the preferred languages if they would like to use a different language than the browser provides. By removing the `&uselang` parameter he will have to set the same language manually on the wiki.

**Comment by Zaczero** [comment]
Okay! I think we should let other websites decide for themselves. If a user prefers to have the same language on each site - they can configure it in the browser once. If a user prefers to have just OSM in a different language - we shouldn't force other websites to behave the same. It also affects links which makes it more difficult to share with others. Do you agree? Or do you have a different perspective?

**Comment by docentYT** [comment]
I think it would be better to remove this parameter.
- It does not affect most users (same osm language as browsers)
- Users using a different language on pages than the browser returns will have to take one more step by changing it on the wiki as well.
- It will be possible to use a different language on the osm page and on the wiki. Currently, every time a user accesses the wiki via url from an osm page, the interface language changes.

**Comment by Zaczero** [comment]
I think the point is that this parameter tries to make the OSM website and wikis look like a single environment—which they are not. The user should decide if they want to change the language globally (in the browser) or in an app (OSM). Otherwise, it also leads to inconsistent behavior because some links will be forcefully translated, and others will not.

I would wait for at least one person to voice their opinion before doing any changes. I mean, you can prepare a PR ahead of time but it will be merged after that.

**Comment by tomekrzymyszkiewicz** [comment]
I think there are a few statements that I could assume (you may or may nor agree):
- the language preferences are a property of the person (their device)
- the language preferences are commonly inherited (from system locales to the web browser, from web browser to the website)
- there always could/should be possibility to make exception (change language of web browser, change language of the website)

These statements lead me to the conclusion that if there is any inheritance of language preferences, it has place vertically. Passing preferred language from OSM to OSM Wiki will be a case of horizontal "inheritance" (in that case, this word start lacking sense).

The safe of getting rid of that is another topic and have to be checked, but this is mine statement in discussion about approach.

**Comment by Zaczero** [comment]
Marking this as completed, thank you for your input!
