### ISSUE TITLE
Wiki: Troubleshooting for: Visual Studio Code: "Git: `pre-commit` not found. Did you forget to activate your virtualenv?"

### ISSUE THREAD

**Issue by docentYT** [Zaczero/openstreetmap-ng#67]
Github does not support pull requests for the Wiki, so I will write my proposal here:

## Visual Studio Code: "Git: `pre-commit` not found. Did you forget to activate your virtualenv?"

If you use WSL on Windows you need to install the [WSL extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl). Then reopen the editor using the `code .` command in the WSL terminal. You will need to [configure git](https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup):
```bash
$ git config --global user.name "John Doe"
$ git config --global user.email johndoe@example.com
```
It is recommended to [set up creditential manager](https://code.visualstudio.com/docs/remote/troubleshooting#_sharing-git-credentials-between-windows-and-wsl).

**Comment by Zaczero** [comment]
Done, Thank You!
