### ISSUE TITLE
"api/0.6/changesets" endpoint without any parameters rising exception

### ISSUE THREAD

**Issue by tomekrzymyszkiewicz** [Zaczero/openstreetmap-ng#68]
# Error description
I noticed an issue when I'm hitting http://127.0.0.1:8000/api/0.6/changesets endpoint without any parameters.
```
INFO:     127.0.0.1:60368 - "GET /api/0.6/changesets HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
...
  File "/home/.../openstreetmap-ng/app/controllers/api06_changeset.py", line 206, in query_changesets
    user_id=user.id if (user is not None) else None,
                        ^^^^
UnboundLocalError: cannot access local variable 'user' where it is not associated with a value
```
The `user` variable is being created only if `display_name_provided` is not None or `user_id_provided` is not None.
# Solution
I see two possible solutions.
## Setting user to None
If `display_name_provided` and `user_id_provided` won't be provided, the `user` could be set to None.
```python
if display_name_provided:
    user = await UserQuery.find_one_by_display_name(display_name)
    if user is None:
        raise_for().user_not_found_bad_request(display_name)
elif user_id_provided:
    user = await UserQuery.find_one_by_id(user_id)
    if user is None:
        raise_for().user_not_found_bad_request(user_id)
else:
	user = None   # <- that guaranting the user variable existence
```
## Checking if user variable exists
If in my opinion worse approach but makes work done.

Instead of checking if user is None (what is currently rising exception):
```python
with options_context(joinedload(Changeset.user).load_only(User.display_name)):
	changesets = await ChangesetQuery.find_many_by_query(
		changeset_ids=changeset_ids,
		user_id=user.id if (user is not None) else None,
		created_before=created_before,
		closed_after=closed_after,
		is_open=True if open else (False if closed else None),
		geometry=geometry,
		sort='asc' if (order == 'newest') else 'desc',
		limit=limit,
	)
```

It could be checked if a variable named `user` exists:
```python
with options_context(joinedload(Changeset.user).load_only(User.display_name)):
	changesets = await ChangesetQuery.find_many_by_query(
		changeset_ids=changeset_ids,
		user_id=user.id if ('user' in locals()) else None,
		created_before=created_before,
		closed_after=closed_after,
		is_open=True if open else (False if closed else None),
		geometry=geometry,
		sort='asc' if (order == 'newest') else 'desc',
		limit=limit,
	)
```

@Zaczero Please let me know if the issue has been correctly diagnosed and what do you think about solutions. I'll provide needed changes in PR after you comment.

**Comment by Zaczero** [comment]
![image](https://github.com/Zaczero/openstreetmap-ng/assets/10835147/3a7c1dd0-b9ed-46c3-af90-230bb20b66de)

It seems like we are missing this one line. When preparing PR make sure to write a simple test in test_api06_changeset that ensures this issue does not happen again (simply make an unauthorized request). I'll assign this issue a bounty given that you have made a very good analysis of the issue :+1:

In long term, we may integrate pypy that would detect those sort of errors.
