### ISSUE TITLE
Let people upload GPX traces without timestamps

### ISSUE THREAD

**Issue by goteusz-maszyk** [Zaczero/openstreetmap-ng#69]
Right now, if a trace doesn't contain any timestamps, it throws an error.

**CODE ANALYISIS:**
https://github.com/Zaczero/openstreetmap-ng/blob/41b2d4131744b091a66809c0dcc387b57838f84e/app/format/api06_trace.py#L97-L103

If a node doesn't contain a timestamp, it skips it, making no-time traces throw an error.

**Comment by Zaczero** [comment]
@goteusz-maszyk Since this is your first bounty, you can keep collecting the funds and let me know whenever you would like to withdraw. It's tracked [here](https://github.com/Zaczero/openstreetmap-ng/wiki/Ledger). Thanks for documenting the issue and preparing a solution :slightly_smiling_face:!
